### ISSUE TITLE
To-Do List!

### ISSUE THREAD

**Issue by waelsucks** [waelsucks/java-chat-application#1]
The following needs to be done:

**General**
- [ ] Finish setting up User class
- [ ] Message objects

**Server**
- [ ] Logging activity on local system
- [ ] Users online
- [ ] Messaging specific users
- [ ] Disconnecting users

**Client**
- [ ] Show online users
- [ ] GUI
- [ ] Save contacts
